#!/bin/bash                                                                        
# Copyright (c) 2019, Johns Hopkins University ( Yenda Trmal <jtrmal@gmail.com> )
# License: Apache 2.0

# Begin configuration section.  
# End configuration section
set -e -o pipefail 
set -o nounset                              # Treat unset variables as an error
set -x

(cd /project/swig-4.0.1; ./configure --without-pcre && make && make install) || exit 1

